- type: latheRecipe
  parent: BaseAmmoRecipe
  id: StripperClip
  result: SpeedLoaderLightRifle
  materials:
    Steel: 100

- type: latheRecipe
  id: SecurityBola
  result: SecurityBola
  completetime: 2
  materials:
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponEnergyCarbineHarmony
  result: WeaponEnergyCarbineHarmony
  completetime: 6
  materials:
    Steel: 800
    Glass: 400
    Plastic: 300

- type: latheRecipe
  id: EnergyCarbineCartridgeHarmony
  result: EnergyCarbineCartridgeHarmony
  completetime: 2
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 250

- type: latheRecipe
  id: EnergyCarbineCartridgeUnstableHarmony
  result: EnergyCarbineCartridgeUnstableHarmony
  completetime: 2
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 250
    Gold: 300
    Plasma: 500

- type: latheRecipe
  id: EnergyCarbineCartridgeXRayHarmony
  result: EnergyCarbineCartridgeXRayHarmony
  completetime: 2
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 250
    Uranium: 300
